### ISSUE TITLE
Avoid overwrite of source files

### ISSUE THREAD

**Issue by caedes** [bellangerq/wysiwyg-editor#4]
It's not really a best practice to overwrite your source files _via_ any Gulp/Grunt/Webpack tasks.

You should take care of them, to enhance the transformations you want to make. Add a `src/` folder to your repository and move all your source files down there. Then build all the transformations of thus files in a `build/` folder ; this one should **not** be part of your repository, so add it to a `.gitignore`.

That way, all the transformations you could implement will be run only once and always on the same version of the file. Avoiding you a number of weird side effects.

That said, you could also add a `gulp build` to help you build all the corresponding transformations you want on your project. 😉

**Comment by bellangerq** [comment]
Yep, I've heard of this good practice but as this was only a small project, I didn't create a `build` task. Thank you for the tip :)
