### ISSUE TITLE
Separate Gulp tasks into multiple files

### ISSUE THREAD

**Issue by caedes** [bellangerq/wysiwyg-editor#5]
Your project will grow, so does your Gulp tasks. This can leave you with a very large and messy `gulpfile.js`. You could split this file into multiple files inside a `gulp-tasks/` directory, then use the `gulp-require-tasks` package 📦 to require all the task files within `gulpfile.js`.

**Comment by bellangerq** [comment]
Nice! I'm not sure if I will add more Gulp tasks for this project (*as it's only a little subproject*) but still it's good to know! Thanks 👍
